spring:
  datasource:
    url: jdbc:postgresql://l2.eren.wtf:5432/gamebuddydb
    username: gamebuddy
    password: 3uT4}dpjK2PUk2#n  #old
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        default_schema: schauth
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  mail:
    host: smtp.gmail.com
    port: 587
    username: noreply.gamebuddy@gmail.com
    password: wkqmkfqtjiidqkks  #old
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  data:
    mongodb:
      uri: mongodb://gamebuddy:hMRbRvpq2dzX1Eqt@ac-ffig6la-shard-00-00.8ymoclu.mongodb.net:27017,ac-ffig6la-shard-00-01.8ymoclu.mongodb.net:27017,ac-ffig6la-shard-00-02.8ymoclu.mongodb.net:27017/?ssl=true&replicaSet=atlas-wt795g-shard-0&authSource=admin&retryWrites=true&w=majority
      database: gamebuddy

springdoc:
  swagger-ui:
    path: /swagger-ui/auth
  api-docs:
    path: /api-docs

update-service:
  url: http://l2.eren.wtf:4566  #old

feign:
  client:
    config:
      default:
        connectTimeout: 15000
        readTimeout: 15000
        loggerLevel: basic

server:
  port: 4567