spring:
  datasource:
    url: jdbc:postgresql://l2.eren.wtf:5432/gamebuddydb
    username: gamebuddy
    password: 3uT4}dpjK2PUk2#n
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        default_schema: schauth
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  mail:
    host: smtp.gmail.com
    port: 587
    username: noreply.gamebuddy@gmail.com
    password: wkqmkfqtjiidqkks
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

springdoc:
  swagger-ui:
    path: /swagger-ui/auth
  api-docs:
    path: /api-docs

update-service:
  url: http://l2.eren.wtf:4566

feign:
  client:
    config:
      default:
        connectTimeout: 15000
        readTimeout: 15000
        loggerLevel: basic

server:
  port: 4567