spring:
  datasource:
    url: jdbc:postgresql://l2.eren.wtf:5432/gamebuddydb
    username: gamebuddy
    password: 3uT4}dpjK2PUk2#n
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        default_schema: schauth
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  mail:
    host: smtp.gmail.com
    port: 587
    username: noreply.gamebuddy@gmail.com
    password: symikbrjjpvsqhlt
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

jwt:
  secret: 4B6250655368566D5970337336763979244226452948404D635166546A576E5A

server:
  port: 4567
